version: "3.9"

x-logging:
  &logging
  logging:
    driver: json-file
    options:
      max-size: "200k"
      max-file: "10"
networks:
  traefik-net:
    name: traefik-net
    driver: bridge

services:
  microservice_gps:
    build: ./gps-api
    expose:
      - 8083
    networks:
      traefik-net:
        aliases:
          - gps.localhost
    deploy:
      mode: replicated
      replicas: 6
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.port=80"
      - "traefik.http.routers.gps.rule=Host(`gps.localhost`)"

  microservice_reward:
    build: ./reward-api
    expose:
      - 8082
    networks:
      traefik-net:
        aliases:
          - reward.localhost
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.port=80"
      - "traefik.http.routers.reward.rule=Host(`reward.localhost`)"

  microservice_users:
    build: ./user-api
    expose:
      - 8081
    networks:
      traefik-net:
        aliases:
          - user.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.port=80"
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"

  traefik:
    #image: traefik:v1.7.14-alpine
    #    image: traefik:v2.3.0
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "81:80"
      - "28081:8080"
    networks:
      traefik-net:
        aliases:
          - gps.localhost
          - user.localhost
          - reward.localhost
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`dash.localhost`)"
      - "traefik.docker.network=traefik-net"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      #- "////./pipe/docker_engine:////./pipe/docker_engine"
      #- "////./pipe/docker_engine:/var/run/docker.sock"
    <<: *logging
    restart: unless-stopped

#http://dash:localhost:8080/dashboard/#/